spring.application.name=WeatherApp
weather.api.key=b8363885fd734be4878155721262406
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json


